[package]
name = "qpl-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"qpl-sys" = { version = "0.1.0", path = "../qpl-sys" }
"bitflags" = { version = "2.4.0" }
